import {renderPaperStock} from './paper-stock.mjs';
import {matchesMonitorDate, localDateValue} from './monitor-filters.mjs';
import {queueState} from './order-queue.mjs';
const $=id=>document.getElementById(id);
let csrf='',orders=[],timer,busy=false,signedIn=false,generation=0,orderSnapshot='';
async function request(path,body){const response=await fetch('/api/v1/monitor/'+path,{method:body?'POST':'GET',credentials:'same-origin',cache:'no-store',signal:AbortSignal.timeout(20000),headers:body?{'Content-Type':'application/json','X-CSRF-Token':csrf}:{},body:body?JSON.stringify(body):undefined});if(!response.ok){const error=new Error(await response.text());error.status=response.status;throw error;}return response.json();}
function node(tag,text,cls){const n=document.createElement(tag);n.textContent=text;if(cls)n.className=cls;return n;}
function showLogin(){generation++;signedIn=false;clearTimeout(timer);orders=[];orderSnapshot='';$('orders').replaceChildren();$('workspace').hidden=true;$('logout').hidden=true;$('login').hidden=false;}
function render(){const host=$('orders');host.replaceChildren();const term=$('search').value.toLowerCase();for(const order of orders){if(!matchesMonitorDate(order.createdAt,$('period').value,$('specific-date').value))continue;const status=queueState(order);if($('filter').value!=='all'&&$('filter').value!==status)continue;if(![order.id,order.customerName,order.customerPhone].join(' ').toLowerCase().includes(term))continue;const card=node('article',''),row=node('div','','row');row.append(node('h2',order.customerName||'Customer'),node('span',status[0].toUpperCase()+status.slice(1),'badge '+status));card.append(row,node('p',new Date(order.createdAt*1000).toLocaleString()+' · #'+order.id.slice(0,8)),node('p',order.customerPhone||''));const money=new Intl.NumberFormat(undefined,{style:'currency',currency:order.currency}).format(order.totalMinor/10**order.currencyMinorUnits);card.append(node('strong',money),node('p',order.status==='pending_payment'?'Payment pending':['paid','dispatched','completed'].includes(order.status)?'Payment recorded':'Payment/order status: '+order.status));for(const d of order.documents)card.append(node('p',d.filename+(d.purged?' · File deleted':'')+(d.printError?' · '+d.printError:'')));host.append(card);}$('result-count').textContent=host.children.length+' matching '+(host.children.length===1?'order':'orders');if(!host.children.length)host.append(node('p','No matching orders.'));}
async function refresh(){if(busy)return;busy=true;const current=generation;try{const data=await request('orders');if(current!==generation)return;csrf=data.csrfToken;if(data.paperStockUnavailable)$('monitor-paper-stock').textContent='Paper stock is temporarily unavailable.';else if(data.paperStock)renderPaperStock($('monitor-paper-stock'),data.paperStock);const snapshot=JSON.stringify(data.orders);const changed=snapshot!==orderSnapshot;orders=data.orders;orderSnapshot=snapshot;signedIn=true;$('business').textContent=data.businessName;document.title=data.businessName+' · Monitor';$('login').hidden=true;$('workspace').hidden=false;$('logout').hidden=false;$('message').textContent='';$('updated').textContent='Updated '+new Date().toLocaleTimeString();if(changed)render();}catch(error){if(current!==generation)return;if(error.status===401)showLogin();$('message').textContent=error.status===401?'Sign in to monitor your shop.':error.message+' Displayed orders may be out of date.';}finally{busy=false;clearTimeout(timer);if(signedIn&&!document.hidden)timer=setTimeout(refresh,5000);}}
$('login').onsubmit=async event=>{event.preventDefault();const button=event.target.querySelector('button');button.disabled=true;try{const data=await request('login',{username:event.target.elements.username.value,password:event.target.elements.password.value});csrf=data.csrfToken;event.target.elements.password.value='';await refresh();}catch(error){$('message').textContent=error.message;}finally{button.disabled=false;}};
$('logout').onclick=async()=>{try{await request('logout',{});showLogin();csrf='';$('message').textContent='Signed out.';}catch(error){$('message').textContent=error.message;}};
$('specific-date').value=localDateValue(new Date());
$('period').onchange=()=>{$('date-field').hidden=$('period').value!=='date';render();};
$('specific-date').onchange=render;
$('filter').onchange=render;$('search').oninput=render;
document.addEventListener('visibilitychange',()=>{clearTimeout(timer);if(!document.hidden&&signedIn)void refresh();});
void refresh();
