import {fromMinorUnits,toMinorUnits} from './money.mjs';
export const combinationKey=e=>[e.paperSize.toUpperCase(),e.colourMode,e.sides].join('|');
export function pricingCombinations(fleet,scope='all'){
 const rows=new Map();for(const p of fleet||[]){if(scope!=='all'&&p.id!==scope)continue;for(const paperSize of p.paperSizes||[])for(const colourMode of p.colourModes||[])for(const sides of p.sidesModes||[]){const e={paperSize,colourMode,sides};rows.set(combinationKey(e),e);}}
 return [...rows.values()].sort((a,b)=>combinationKey(a).localeCompare(combinationKey(b)));
}
const el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;};
export function createPricingGrid(client,getRole){
 const root=document.getElementById('pricing-panel');let scope='all',data,dirty=false,busy=false;
 root.classList.add('pricing-workspace');
 root.innerHTML=`<header class="pg-header"><div><small>BUSINESS SETUP</small><h1>Pricing Grid</h1><p>Set your rates for the paper sizes your enabled printers offer.</p></div><button id="pg-save" type="button" class="btn btn--primary">Save prices</button></header><div class="pg-content"><section class="pg-scope"><label>Apply prices to<select id="pg-scope"><option value="all">All enabled printers â€” shared rates</option></select></label><p>Shared rates apply to all compatible printers. Select a printer to set different rates; blank override fields use the shared rate. Quotes use this grid. Legacy service prices do not override it.</p></section><section id="pg-overrides" class="pg-scope" hidden></section><p id="pg-message" role="status" aria-live="polite"></p><form id="pg-form"><section class="pg-grid"><div class="pg-grid-head"><h2>Print rates</h2><p id="pg-unit"></p><p>One duplex sheet can contain two printed sides. Copies and pages per sheet are included in the sheet count. Leave a shared rate blank to omit that combination.</p></div><div id="pg-rows"></div></section><label class="pg-confirm"><input type="checkbox" id="pg-free"> I intend to offer any zero-price rates or quantity tiers entered here.</label><label class="pg-confirm" id="pg-precision-label" hidden><input type="checkbox" id="pg-precision"> I reviewed the prices after the currency or decimal precision change.</label></form></div>`;
 const $=id=>root.querySelector('#'+id);const note=text=>{$('pg-message').textContent=text;};
 root.addEventListener('input',()=>{dirty=true;});
 $('pg-scope').onchange=async e=>{if(dirty&&!confirm('Discard unsaved pricing changes and switch printer?')){e.target.value=scope;return;}scope=e.target.value;await refresh();};
 $('pg-save').onclick=()=>save();$('pg-form').onsubmit=e=>{e.preventDefault();void save();};
 function field(label,value,kind='amount'){const wrap=el('label','pg-field',label),input=el('input');input.value=value;input.dataset.kind=kind;input.inputMode=kind==='quantity'?'numeric':'decimal';if(kind==='quantity'){input.type='number';input.min='2';input.step='1';}wrap.append(input);return wrap;}
 function tierRow(parent,tier,mu){const row=el('div','pg-tier');row.append(field('From sheets',tier?.minQuantity??'','quantity'),field('Price / sheet',tier?fromMinorUnits(tier.unitPriceMinor,mu):''));const remove=el('button','pg-remove','Remove tier');remove.type='button';remove.onclick=()=>{row.remove();dirty=true;};row.append(remove);parent.append(row);}
 async function refresh(){try{data=await client.request('GET','/api/v1/owner/pricing/grid/'+scope);if(scope!=='all'&&!(data.fleet||[]).some(p=>p.id===scope)){scope='all';return refresh();}render();dirty=false;}catch(e){note(e.message);}}
 function render(){
 const summary=$('pg-overrides');summary.replaceChildren();summary.hidden=scope!=='all'||!Object.keys(data.overrides||{}).length;
 if(!summary.hidden){summary.append(el('strong','','Printer overrides are active — these take priority over shared rates.'));for(const [id,rates] of Object.entries(data.overrides)){const printer=(data.printers||[]).find(p=>p.id===id);const block=el('div');block.append(el('strong','',printer?.displayName||printer?.queueName||id));for(const rate of rates.entries||[])block.append(el('p','',`${rate.paperSize} · ${rate.colourMode} · ${rate.sides}: ${fromMinorUnits(rate.unitPriceMinor,rates.currencyMinorUnits)} ${rates.currency}/sheet${rate.tiers?.length ? ' (quantity discounts configured)' : ''}`));const edit=el('button','btn btn--secondary','Edit printer rates');edit.type='button';edit.onclick=async()=>{if(dirty&&!confirm('Discard unsaved shared prices?'))return;scope=id;await refresh();};block.append(edit);summary.append(block);}}
 const book=data.book;const select=$('pg-scope');select.replaceChildren(new Option('All enabled printers â€” shared rates','all'));for(const p of data.printers||[]){if((data.fleet||[]).some(f=>f.id===p.id))select.add(new Option(p.displayName||p.queueName,p.id));}select.value=scope;
 $('pg-unit').textContent=`${book.currency} per physical sheet Â· ${scope==='all'?'Shared rates':'Printer-specific overrides'}`;
 $('pg-precision-label').hidden=!(book.precisionMismatch||book.currencyMismatch);$('pg-precision').checked=false;$('pg-free').checked=false;
 const rows=$('pg-rows');rows.replaceChildren();const combos=pricingCombinations(data.fleet,scope);const saved=new Map((book.entries||[]).map(e=>[combinationKey(e),e]));const shared=new Map((data.shared.entries||[]).map(e=>[combinationKey(e),e]));
 for(const combo of combos){const entry=saved.get(combinationKey(combo)),base=shared.get(combinationKey(combo));const row=el('article','pg-row');row.dataset.combo=JSON.stringify(combo);const title=el('div','pg-description');title.append(el('strong','',combo.paperSize),el('span',combo.colourMode==='colour'?'pg-colour':'pg-mono',combo.colourMode==='colour'?'Colour':'Black & white'),el('span','',combo.sides==='one-sided'?'Single-sided':combo.sides==='two-sided-long-edge'?'Duplex Â· long edge':'Duplex Â· short edge'));row.append(title);
 const amount=field('Price / sheet ('+book.currency+')',entry?fromMinorUnits(entry.unitPriceMinor,book.currencyMinorUnits):'');amount.querySelector('input').placeholder=scope==='all'?'Not offered':base?'Shared: '+fromMinorUnits(base.unitPriceMinor,data.shared.currencyMinorUnits):'No shared rate';row.append(amount);
 const details=el('details','pg-tiers');details.append(el('summary','',`Quantity discounts${entry?.tiers?.length?' ('+entry.tiers.length+')':''}`));const list=el('div','pg-tier-list');for(const tier of entry?.tiers||[])tierRow(list,tier,book.currencyMinorUnits);const add=el('button','btn btn--ghost','+ Add quantity tier');add.type='button';add.onclick=()=>{tierRow(list,null,book.currencyMinorUnits);dirty=true;};details.append(el('p','','A tier applies to this combination only. Enter a base price when setting printer-specific tiers.'),list,add);row.append(details);rows.append(row);}
 if(!combos.length)rows.append(el('p','pg-empty','No enabled paper sizes are available. Open Printers, confirm the sizes you offer, and enable the printer.'));
 if(book.precisionMismatch||book.currencyMismatch)note('Currency settings changed. Review every amount before saving.');
 else note(scope==='all'?'Set prices here first, then add optional printer overrides.':'Blank fields inherit shared rates. Saving an empty override grid restores shared rates for this printer.');
 $('pg-save').disabled=getRole()!=='owner'||!book.currencySupported||!combos.length||busy;
 for(const control of $('pg-form').querySelectorAll('input,button'))control.disabled=getRole()!=='owner'||busy;
 }
 async function save(){if(busy)return;try{
 const entries=[];const mu=data.book.derivedMinorUnits;
 for(const row of $('pg-rows').querySelectorAll('.pg-row')){const amount=row.querySelector(':scope > .pg-field input').value.trim();const tiers=[...row.querySelectorAll('.pg-tier')].map(t=>({minQuantity:Number(t.querySelector('[data-kind="quantity"]').value),unitPriceMinor:toMinorUnits(t.querySelector('[data-kind="amount"]').value,mu)}));if(!amount){if(tiers.length)throw new Error('Enter a base price for every row with quantity tiers.');continue;}entries.push({...JSON.parse(row.dataset.combo),unitPriceMinor:toMinorUnits(amount,mu),tiers});}
 busy=true;$('pg-save').disabled=true;$('pg-scope').disabled=true;
 await client.request('PUT','/api/v1/owner/pricing/grid/'+scope,{entries,confirmFreePricing:$('pg-free').checked,confirmPrecisionCorrection:$('pg-precision').checked});await refresh();note('Prices saved. New quotes use these rates; existing confirmed orders retain their totals.');
 }catch(e){note(e.message);}finally{busy=false;$('pg-save').disabled=getRole()!=='owner'||!data?.book.currencySupported;$('pg-scope').disabled=false;for(const control of $('pg-form').querySelectorAll('input,button'))control.disabled=getRole()!=='owner';}}
 return {refresh,refreshIfClean:()=>{if(!dirty&&!busy)void refresh();}};
}
