import {invoiceSettingsCard} from './printer-invoices.mjs';
const node=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;};
const button=(label,fn,cls='oq-button')=>{const b=node('button',cls,label);b.type='button';b.onclick=fn;return b;};
export function enabledPapers(verifications=[]) {
 return new Set(verifications.filter(v=>v.capabilityType==='paper_size'&&!v.invalidatedAt&&['verified','confirmed','tested'].includes(v.status)).map(v=>v.capabilityKey));
}
export function createPrinterSetup(client,getRole) {
 const root=document.getElementById('printers-panel'),enrollment=root.querySelector('details');
 let printers=[],selected=null,filter='all',search='',busy=false;
 root.classList.add('order-workspace','printer-workspace');
 root.innerHTML=`<header class="oq-top"><div class="oq-title"><span class="oq-clock" aria-hidden="true">▤</span><div><small>SHOP SETUP</small><h1>Printers</h1><p>Choose where customer documents print and which paper sizes you offer.</p></div></div><div id="ps-metrics" class="ps-metrics"></div></header><div class="ps-toolbar"><nav id="ps-tabs" aria-label="Printer filter"></nav><div class="oq-filters"><label class="oq-search"><input id="ps-search" type="search" aria-label="Search printers" placeholder="Search printer name or location…"></label><button id="printers-refresh" class="oq-button" type="button">↻ Refresh printers</button></div><p id="printers-message" role="status" aria-live="polite"></p></div><div class="ps-steps"><span><b>1</b> Choose a printer</span><span><b>2</b> Load paper & print a test</span><span><b>3</b> Confirm sizes & enable printer</span></div><div class="ps-layout"><aside id="ps-list"></aside><main id="ps-detail"></main></div><details class="ps-help"><summary>Printer missing? Start here</summary><p>Install the printer in Windows Settings → Bluetooth & devices → Printers & scanners. Turn it on, connect USB or the shop network, then refresh this list. Windows discovery may take a few seconds.</p><p>The Windows service needs a printer installed for this computer. A printer available only to another Windows user may not appear.</p></details>`;
 if(enrollment){enrollment.classList.add('ps-help');enrollment.querySelector('summary').textContent='Advanced: add a printer manually';root.append(enrollment);}
 const $=id=>root.querySelector('#'+id);
 for(const nav of document.querySelectorAll('.nav-item')){nav.title=nav.textContent.trim();nav.setAttribute('aria-label',nav.title);}
 const tell=text=>{$('printers-message').textContent=text;};
 $('ps-search').oninput=e=>{search=e.target.value;render();};
 $('printers-refresh').onclick=()=>refresh();
 async function refresh(){try{const data=await client.request('GET','/api/v1/owner/printers');printers=await Promise.all((data.printers||[]).map(async p=>({...p,verifications:(await client.request('GET',`/api/v1/owner/printers/${p.id}/verifications`)).verifications||[]})));if(!printers.some(p=>p.id===selected))selected=printers[0]?.id;render();}catch(e){tell(e.message);}}
 async function change(fn,success){if(busy)return;busy=true;render();try{const result=await fn();tell(typeof success==='function'?success(result):success);await refresh();}catch(e){tell(e.message);}finally{busy=false;render();}}
 function render(){
 $('ps-metrics').textContent=`${printers.length} printers · ${printers.filter(p=>p.enabled).length} enabled`;
 const tabs=$('ps-tabs');tabs.replaceChildren();for(const [key,label] of [['all','All printers'],['enabled','Enabled'],['disabled','Disabled']]){const count=printers.filter(p=>key==='all'||p.enabled===(key==='enabled')).length;const b=button(`${label} ${count}`,()=>{filter=key;render();},'oq-tab'+(filter===key?' active':''));b.setAttribute('aria-pressed',String(filter===key));tabs.append(b);}
 const list=$('ps-list');list.replaceChildren();const visible=printers.filter(p=>(filter==='all'||p.enabled===(filter==='enabled'))&&[p.displayName,p.queueName,p.location].join(' ').toLowerCase().includes(search.toLowerCase()));
 for(const p of visible){const row=button('',()=>{selected=p.id;render();},'ps-printer'+(selected===p.id?' selected':''));row.append(node('strong','',p.displayName||p.queueName),node('span','',p.location||p.queueName),node('small',p.enabled?'ps-enabled':'',p.enabled?'Enabled for customer orders':'Disabled for customer orders'));list.append(row);}
 if(!visible.length)list.append(node('p','ps-empty',printers.length?'No printers match this filter.':'No printers found. Install a printer in Windows, then refresh.'));
 const main=$('ps-detail');main.replaceChildren();const p=printers.find(p=>p.id===selected);if(!p){main.append(node('p','ps-empty','Your printers and paper sizes will appear here.'));return;}
 const head=node('header','ps-detail-head'),info=node('div');info.append(node('small','oq-eyebrow','PRINTER SETUP'),node('h2','',p.displayName||p.queueName),node('p','',`${p.location||'Shop printer'} · ${p.isDefault?'Windows default · ':''}${p.status||'Status unknown'}`));head.append(info);
 const owner=getRole()==='owner';
 const toggle=button(p.enabled?'Disable printer':'Enable printer',()=>change(()=>client.request('PUT',`/api/v1/owner/printers/${p.id}/${p.enabled?'disable':'enable'}`,{}),p.enabled?'Printer disabled for new customer orders.':'Printer enabled for customer orders.'),'oq-button '+(p.enabled?'':'oq-primary'));toggle.disabled=busy||!owner||(!p.enabled&&!enabledPapers(p.verifications).size);head.append(toggle);main.append(head);if(!p.enabled&&!enabledPapers(p.verifications).size)main.append(node('p','ps-note','Confirm at least one paper size below to enable this printer.'));
 const card=node('section','ps-paper-card');card.append(node('h3','','Paper sizes'),node('p','ps-note','Load the matching paper in this printer, then print one test sheet. Check the output before selecting “Confirm & enable”. Enabled sizes become available when this printer is enabled and pricing is configured.'));
 const sizes=p.capabilities?.paperSizes||[],enabled=enabledPapers(p.verifications);
 const table=node('table','ps-paper-table');const thead=node('thead'),tr=node('tr');for(const label of ['Paper size','Customer availability','Test & confirm'])tr.append(node('th','',label));thead.append(tr);table.append(thead);const body=node('tbody');
 for(const size of sizes){const row=node('tr'),name=node('td'),status=node('td'),actions=node('td');name.append(node('strong','',size.key),node('small','',size.widthMm&&size.heightMm?`${size.widthMm} × ${size.heightMm} mm`:'Dimensions unavailable'));status.append(node('span','oq-pill '+(enabled.has(size.key)?'printing':''),enabled.has(size.key)?'Enabled':'Not enabled'));const group=node('div','oq-actions');
 const test=button('Test Print',()=>change(()=>client.request('POST',`/api/v1/owner/printers/${p.id}/test-print`,{paper:size.key}),result=>`${size.key} test sent to ${result.queue} (job ${result.jobId}). Check the printed sheet, then confirm the size.`),'oq-button oq-release');test.setAttribute('aria-label','Test Print '+size.key);test.disabled=busy||!owner||p.backend!=='windows'||!size.widthMm||!size.heightMm;
 const allow=button(enabled.has(size.key)?'Disable size':'Confirm & enable',()=>{const on=!enabled.has(size.key);if(on&&!window.confirm(`Confirm ${size.key} prints correctly on ${p.displayName||p.queueName}? This enables the size for customer orders.`))return;void change(()=>client.request('PUT',`/api/v1/owner/printers/${p.id}/paper`,{paper:size.key,enabled:on}),`${size.key} ${on?'enabled':'disabled'} for this printer.`);});allow.disabled=busy||!owner;group.append(test,allow);actions.append(group);row.append(name,status,actions);body.append(row);}
 table.append(body);card.append(table);if(!sizes.length)card.append(node('p','ps-empty','The driver has not reported paper sizes. Check the Windows printer driver and refresh.'));main.append(card);
 const caps=node('section','ps-capabilities');caps.append(node('h3','','Other printer capabilities'),node('p','',(p.capabilities?.colourModes||[]).map(v=>v==='monochrome'?'Black & white':v==='colour'?'Colour':v).join(' · ')||'Colour capability unavailable'),node('p','',(p.capabilities?.sidesModes||[]).map(v=>v==='one-sided'?'Single-sided':v==='two-sided-long-edge'?'Duplex: long edge':v==='two-sided-short-edge'?'Duplex: short edge':v).join(' · ')||'Duplex capability unavailable'),node('small','','Capabilities come from the installed driver. Test Print uses one single-sided, black & white sheet.'));main.append(caps);
 main.append(invoiceSettingsCard(client,p,owner,busy));
 if(p.backend!=='windows')main.append(node('p','ps-note','To test this printer on Windows, install its Windows driver and choose its Windows queue.'));
 if(!owner)main.append(node('p','ps-note','Only the shop owner can change printer setup or send test prints.'));
 const details=node('details','ps-technical');details.append(node('summary','','Printer details'),node('p','',`Queue: ${p.queueName}`),node('p','',`Driver: ${p.driverName||'Not reported'}`),node('p','',`Connection: ${p.backend}`));if(owner){const remove=button('Remove printer',()=>{if(!window.confirm('Remove this printer? Existing orders are retained.'))return;void change(()=>client.request('DELETE','/api/v1/owner/printers/'+p.id,{}),'Printer removed.');},'oq-button oq-danger');remove.disabled=busy;details.append(remove);}main.append(details);
 }
 return {refresh};
}
